CREATE TABLE "THIRD_PARTY" (
  "ID" UUID PRIMARY KEY,
  "TYPE" "VARCHAR(20)",
  "DOCUMENT_TYPE" "VARCHAR(10)",
  "DOCUMENT_NUMBER" "VARCHAR(30)" UNIQUE,
  "NAME" "VARCHAR(255)",
  "EMAIL" "VARCHAR(100)",
  "PHONE" "VARCHAR(30)",
  "ADDRESS" "VARCHAR(255)",
  "CITY" "VARCHAR(100)",
  "CONTACT_NAME" "VARCHAR(100)",
  "CREDIT_DAYS_ID" UUID NOT NULL,
  "NOTES" TEXT,
  "RETE_IVA" BOOL,
  "CREATED_AT" TIMESTAMP,
  "IS_ACTIVE" BOOLEAN
);

CREATE TABLE "CREDIT_DAYS" (
  "ID" UUID PRIMARY KEY,
  "CREDIT_DAYS" INTEGER,
  "IS_ACTIVE" BOOLEAN
);

CREATE TABLE "USER" (
  "ID" UUID PRIMARY KEY,
  "EMPLOYEE_ID" uuid NOT NULL,
  "EMAIL" VARCHAR UNIQUE,
  "PASSWORD_HASH" VARCHAR,
  "IS_ADMIN" BOOLEAN,
  "IS_PLANT" BOOLEAN,
  "IS_ACTIVE" BOOLEAN
);

CREATE TABLE "EMPLOYEE" (
  "ID" UUID PRIMARY KEY,
  "CODE" VARCHAR UNIQUE,
  "FIRST_NAME" VARCHAR,
  "LAST_NAME" VARCHAR,
  "EMAIL" "VARCHAR(100)",
  "ADDRESS" "VARCHAR(100)",
  "PHONE" VARCHAR,
  "HIRE_DATE" DATE,
  "ROLE" "VARCHAR(50)",
  "AREA_ID" UUID NOT NULL,
  "IS_ACTIVE" BOOLEAN
);

CREATE TABLE "AREA" (
  "ID" UUID PRIMARY KEY,
  "AREA" "VARCHAR(50)"
);

CREATE TABLE "PRODUCT" (
  "ID" UUID PRIMARY KEY,
  "CODE" VARCHAR UNIQUE,
  "NAME" "VARCHAR(150)",
  "PRODUCT_TYPE" "VARCHAR(20)",
  "PRODUCT_CATEGORY_ID" UUID NOT NULL,
  "PURCHASE_UNIT" "VARCHAR(20)" NOT NULL,
  "CONSUMPTION_UNIT" "VARCHAR(20)" NOT NULL,
  "CONVERSION_FACTOR" "DECIMAL(14,4)",
  "MINIMUM_STOCK" "DECIMAL(14,4)",
  "AVERAGE_COST" "DECIMAL(14,2)",
  "IS_ACTIVE" BOOLEAN
);

CREATE TABLE "PRODUCT_CATEGORY" (
  "ID" UUID PRIMARY KEY,
  "CATEGORY" "VARCHAR(40)"
);

CREATE TABLE "INVENTORY_BALANCE" (
  "PRODUCT_ID" UUID UNIQUE NOT NULL,
  "CURRENT_STOCK" "DECIMAL(14,4)",
  "RESERVED_STOCK" "DECIMAL(14,4)",
  "UPDATED_AT" TIMESTAMP
);

CREATE TABLE "STOCK_MOVEMENT" (
  "ID" UUID PRIMARY KEY,
  "PRODUCT_ID" UUID NOT NULL,
  "MOVEMENT_TYPE" "VARCHAR(20)",
  "SOURCE_TYPE" "VARCHAR(30)",
  "SOURCE_ID" uuid,
  "QUANTITY" "DECIMAL(14,4)",
  "UNIT_COST" "DECIMAL(14,2)",
  "NOTES" TEXT,
  "CREATED_AT" TIMESTAMP
);

CREATE TABLE "PURCHASE_ORDER" (
  "ID" UUID PRIMARY KEY,
  "NUMBER" VARCHAR UNIQUE,
  "SUPPLIER_ID" UUID NOT NULL,
  "STATUS" "VARCHAR(20)",
  "PRIORITY" "VARCHAR(20)",
  "NOTES" TEXT,
  "CREATED_AT" TIMESTAMP,
  "RECEIVED_AT" DATE,
  "EXPECTED_DELIVERY_DATE" DATE
);

CREATE TABLE "PURCHASE_REQUEST" (
  "ID" UUID PRIMARY KEY,
  "NUMBER" "VARCHAR(20)" UNIQUE,
  "WORK_ORDER_ID" UUID NOT NULL,
  "REQUESTED_BY" UUID,
  "STATUS" "VARCHAR(30)",
  "PRIORITY" "VARCHAR(20)",
  "NOTES" TEXT,
  "CREATED_AT" TIMESTAMP,
  "IS_ACTIVE" BOOLEAN
);

CREATE TABLE "PURCHASE_REQUEST_ITEM" (
  "ID" UUID PRIMARY KEY,
  "PRODUCT_REQUEST_ID" UUID NOT NULL,
  "PRODUCT_ID" UUID NOT NULL,
  "REQUIRED_QUANTITY" "DECIMAL(14,4)"
);

CREATE TABLE "PURCHASE_ORDER_ITEM" (
  "ID" UUID PRIMARY KEY,
  "PURCHASE_ORDER_ID" UUID NOT NULL,
  "PRODUCT_ID" UUID NOT NULL,
  "QUANTITY" "DECIMAL(14,4)",
  "UNIT_COST" "DECIMAL(14,2)",
  "RECEIVED_QUANTITY" "DECIMAL(14,4)",
  "PURCHASE_REQUEST_ITEM_ID" UUID
);

CREATE TABLE "QUOTE" (
  "ID" UUID PRIMARY KEY,
  "NUMBER" "VARCHAR(30)" UNIQUE,
  "CLIENT_ID" UUID NOT NULL,
  "STATUS" "VARCHAR(50)",
  "VALID_UNTIL" DATE,
  "TOTAL" "DECIMAL(14,2)",
  "NOTES" varchar(100),
  "APROVED_AT" TIMESTAMP,
  "IS_ACTIVE" BOOLEAN
);

CREATE TABLE "QUOTE_ITEM" (
  "ID" UUID PRIMARY KEY,
  "QUOTE_ID" uuid NOT NULL,
  "DESCRIPTION" "VARCHAR(50)" NOT NULL,
  "QUANTITY" integer NOT NULL,
  "UNIT_PRICE" integer NOT NULL,
  "TOTAL" INTEGER
);

CREATE TABLE "WORK_ORDER" (
  "ID" UUID PRIMARY KEY,
  "NUMBER" VARCHAR UNIQUE,
  "TYPE" "VARCHAR(30)",
  "QUOTE_ID" UUID,
  "ORIGINAL_WORK_ORDER_ID" UUID,
  "CLIENT_ID" UUID NOT NULL,
  "PRIORITY" "VARCHAR(20)",
  "STATUS" "VARCHAR(30)",
  "DESCRIPTION" TEXT,
  "ESTIMATED_DELIVERY_DATE" DATE,
  "WORK_ORDER_FILE_ID" UUID,
  "UNIT_PRICE" "DECIMAL(14,2)",
  "NOTES" TEXT,
  "APPROVED_AT" TIMESTAMP,
  "STARTED_AT" TIMESTAMP,
  "COMPLETED_AT" TIMESTAMP,
  "DELIVERED_AT" TIMESTAMP,
  "CREATED_AT" TIMESTAMP
);

CREATE TABLE "WORK_ORDER_FILE" (
  "ID" UUID PRIMARY KEY,
  "WORK_ORDER_ID" uuid NOT NULL,
  "FILE_TYPE_ID" UUID NOT NULL,
  "OBJECT_KEY" varchar(50),
  "ORIGINAL_NAME" varchar(50),
  "CONTENT_TYPE" varchar(50),
  "SIZE" BIGINT,
  "UPLOADED_BY" varchar(50),
  "CREATED_AT" timestamp,
  "IS_ACTIVE" BOOLEAN
);

CREATE TABLE "WORK_ORDER_COMMENT" (
  "ID" UUID PRIMARY KEY,
  "WORK_ORDER_ID" uuid NOT NULL,
  "USER_ID" UUID NOT NULL,
  "COMMENT" "VARCHAR(200)",
  "CREATED_AT" TIMESTAMP
);

CREATE TABLE "FILE_TYPE" (
  "ID" UUID PRIMARY KEY,
  "TYPE" "VARCHAR(50)"
);

CREATE TABLE "WORK_ORDER_MATERIAL" (
  "ID" UUID PRIMARY KEY,
  "WORK_ORDER_ID" UUID NOT NULL,
  "PRODUCT_ID" UUID NOT NULL,
  "ESTIMATED_QUANTITY" "DECIMAL(14,4)",
  "EXTRA_QUANTITY" "DECIMAL(14,4)",
  "CONSUMED_QUANTITY" "DECIMAL(14,4)"
);

CREATE TABLE "WORK_ORDER_STAGE" (
  "ID" UUID PRIMARY KEY,
  "WORK_ORDER_ID" UUID NOT NULL,
  "STAGE" "VARCHAR(30)",
  "SEQUENCE" integer,
  "STATUS" "VARCHAR(20)",
  "STARTED_AT" TIMESTAMP,
  "FINISHED_AT" TIMESTAMP,
  "ESTIMATED_MINUTES" INTEGER,
  "TOTAL_TIME" INTEGER,
  "IS_ACTIVE" BOOLEAN
);

CREATE TABLE "WORK_ORDER_STAGE_LOG" (
  "ID" UUID PRIMARY KEY,
  "WORK_ORDER_STAGE_ID" UUID NOT NULL,
  "EMPLOYEE_ID" UUID NOT NULL,
  "ACTION" "VARCHAR(20)",
  "EVENT_TIME" TIMESTAMP
);

CREATE TABLE "WORK_ORDER_ASSIGNMENT" (
  "ID" UUID PRIMARY KEY,
  "WORK_ORDER_STAGE_ID" UUID NOT NULL,
  "EMPLOYEE_ID" UUID NOT NULL
);

CREATE TABLE "DELIVERY_NOTE" (
  "ID" UUID PRIMARY KEY,
  "NUMBER" VARCHAR UNIQUE,
  "CLIENT_ID" UUID NOT NULL,
  "DELIVERY_DATE" DATE,
  "RECEIVED_BY" "VARCHAR(100)",
  "NOTES" TEXT,
  "SIIGO_INVOICE_ID" "VARCHAR(100)",
  "SIIGO_INVOICE_NUMBER" "VARCHAR(100)",
  "SIIGO_STATUS" "VARCHAR(20)",
  "STATUS" "VARCHAR(20)",
  "CREATED_AT" TIMESTAMP
);

CREATE TABLE "DELIVERY_NOTE_ITEM" (
  "DELIVERY_NOTE_ID" UUID NOT NULL,
  "WORK_ORDER_ID" UUID NOT NULL,
  "DESCRIPTION" "VARCHAR(255)",
  "QUANTITY" "DECIMAL(14,2)",
  "TOTAL_PRICE" "DECIMAL(14,2)"
);

CREATE TABLE "SIIGO_SYNC_LOG" (
  "ID" UUID PRIMARY KEY,
  "ENTITY_TYPE" "VARCHAR(30)",
  "ENTITY_ID" UUID,
  "REQUEST" JSON,
  "RESPONSE" JSON,
  "STATUS" "VARCHAR(20)",
  "CREATED_AT" TIMESTAMP,
  "IS_ACTIVE" BOOLEAN
);

CREATE TABLE "AUDIT_LOG" (
  "ID" UUID PRIMARY KEY,
  "USER_ID" UUID,
  "ENTITY" "VARCHAR(50)",
  "ENTITY_ID" UUID,
  "ACTION" "VARCHAR(20)",
  "CHANGES" JSON,
  "CREATED_AT" TIMESTAMP,
  "IS_ACTIVE" BOOLEAN
);

ALTER TABLE "STOCK_MOVEMENT" ADD FOREIGN KEY ("PRODUCT_ID") REFERENCES "PRODUCT" ("ID") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "PURCHASE_ORDER" ADD FOREIGN KEY ("SUPPLIER_ID") REFERENCES "THIRD_PARTY" ("ID") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "PURCHASE_ORDER_ITEM" ADD FOREIGN KEY ("PRODUCT_ID") REFERENCES "PRODUCT" ("ID") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "PURCHASE_ORDER_ITEM" ADD FOREIGN KEY ("PURCHASE_ORDER_ID") REFERENCES "PURCHASE_ORDER" ("ID") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "WORK_ORDER" ADD FOREIGN KEY ("CLIENT_ID") REFERENCES "THIRD_PARTY" ("ID") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "WORK_ORDER_MATERIAL" ADD FOREIGN KEY ("WORK_ORDER_ID") REFERENCES "WORK_ORDER" ("ID") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "WORK_ORDER_MATERIAL" ADD FOREIGN KEY ("PRODUCT_ID") REFERENCES "PRODUCT" ("ID") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "WORK_ORDER_STAGE" ADD FOREIGN KEY ("WORK_ORDER_ID") REFERENCES "WORK_ORDER" ("ID") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "WORK_ORDER_STAGE_LOG" ADD FOREIGN KEY ("WORK_ORDER_STAGE_ID") REFERENCES "WORK_ORDER_STAGE" ("ID") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "WORK_ORDER_STAGE_LOG" ADD FOREIGN KEY ("EMPLOYEE_ID") REFERENCES "EMPLOYEE" ("ID") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "WORK_ORDER_ASSIGNMENT" ADD FOREIGN KEY ("WORK_ORDER_STAGE_ID") REFERENCES "WORK_ORDER_STAGE" ("ID") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "WORK_ORDER_ASSIGNMENT" ADD FOREIGN KEY ("EMPLOYEE_ID") REFERENCES "EMPLOYEE" ("ID") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "DELIVERY_NOTE" ADD FOREIGN KEY ("CLIENT_ID") REFERENCES "THIRD_PARTY" ("ID") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "DELIVERY_NOTE_ITEM" ADD FOREIGN KEY ("WORK_ORDER_ID") REFERENCES "WORK_ORDER" ("ID") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "DELIVERY_NOTE_ITEM" ADD FOREIGN KEY ("DELIVERY_NOTE_ID") REFERENCES "DELIVERY_NOTE" ("ID") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "THIRD_PARTY" ADD FOREIGN KEY ("CREDIT_DAYS_ID") REFERENCES "CREDIT_DAYS" ("ID") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "EMPLOYEE" ADD FOREIGN KEY ("AREA_ID") REFERENCES "AREA" ("ID") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "WORK_ORDER_FILE" ADD FOREIGN KEY ("WORK_ORDER_ID") REFERENCES "WORK_ORDER" ("ID") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "WORK_ORDER_FILE" ADD FOREIGN KEY ("FILE_TYPE_ID") REFERENCES "FILE_TYPE" ("ID") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "WORK_ORDER" ADD FOREIGN KEY ("QUOTE_ID") REFERENCES "QUOTE" ("ID") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "QUOTE_ITEM" ADD FOREIGN KEY ("QUOTE_ID") REFERENCES "QUOTE" ("ID") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "INVENTORY_BALANCE" ADD FOREIGN KEY ("PRODUCT_ID") REFERENCES "PRODUCT" ("ID") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "PRODUCT" ADD FOREIGN KEY ("PRODUCT_CATEGORY_ID") REFERENCES "PRODUCT_CATEGORY" ("ID") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "PURCHASE_REQUEST_ITEM" ADD FOREIGN KEY ("PRODUCT_ID") REFERENCES "PRODUCT" ("ID") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "PURCHASE_REQUEST" ADD FOREIGN KEY ("WORK_ORDER_ID") REFERENCES "WORK_ORDER" ("ID") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "WORK_ORDER_COMMENT" ADD FOREIGN KEY ("WORK_ORDER_ID") REFERENCES "WORK_ORDER" ("ID") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "WORK_ORDER_COMMENT" ADD FOREIGN KEY ("USER_ID") REFERENCES "USER" ("ID") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "PURCHASE_ORDER_ITEM" ADD FOREIGN KEY ("PURCHASE_REQUEST_ITEM_ID") REFERENCES "PURCHASE_REQUEST_ITEM" ("ID") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "USER" ADD FOREIGN KEY ("EMPLOYEE_ID") REFERENCES "EMPLOYEE" ("ID") DEFERRABLE INITIALLY IMMEDIATE;
