from .base import *

# Seguridad, S3, dominios

DEBUG = False

ALLOWED_HOSTS = env.list("ALLOWED_HOSTS")


SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

SESSION_COOKIE_SECURE = True

CSRF_COOKIE_SECURE = True

SECURE_BROWSER_XSS_FILTER = True

SECURE_CONTENT_TYPE_NOSNIFF = True